### PR TITLE
Issue #37: Show remaining balance on Transactions page AND fix bar chart

### PR DESCRIPTION
**Pull request by ghuarng**
Shows a running "Remaining Balance" statistic.
Now with multi-user support.

Fixes bar chart component -- used to fetch all transactions of the user

### CODE REVIEW

**Review by cpshan — APPROVED** [review]
LGTM

**Review by mbrewer05 — APPROVED** [review]

**Review by ghost — DISMISSED** [review]
In transactionpage.js, it should return the get response

**Review by ghost — COMMENTED** [review]
LGTM

**Review by ghost — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]
lgtm

**Review by cpshan — APPROVED** [review]
Awesome

**Pull request merged**
